/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    McImg: typeof import('./src/components/custom-components/McImg/index.vue')['default']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
