/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlNestWidget: typeof import('./src/components/control/ControlNestWidget.vue')['default']
    CustomSchemaTemplate: typeof import('./src/components/control/CustomSchemaTemplate.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderWrapper: typeof import('./src/components/custom-schema-template/HeaderWrapper.vue')['default']
    LabelWrapper: typeof import('./src/components/custom-schema-template/LabelWrapper.vue')['default']
    McContainer: typeof import('./src/components/custom-components/McContainer/McContainer.vue')['default']
    McImg: typeof import('./src/components/custom-components/McImg/McImg.vue')['default']
    McTab: typeof import('./src/components/custom-components/McTab/McTab.vue')['default']
    McTitle: typeof import('./src/components/custom-components/McTitle/McTitle.vue')['default']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaArray: typeof import('./src/components/custom-schema-template/components/SchemaArray/SchemaArray.vue')['default']
    SchemaColor: typeof import('./src/components/custom-schema-template/components/SchemaColor/SchemaColor.vue')['default']
    SchemaNumber: typeof import('./src/components/custom-schema-template/components/SchemaNumber/SchemaNumber.vue')['default']
    SchemaObject: typeof import('./src/components/custom-schema-template/components/SchemaObject/SchemaObject.vue')['default']
    SchemaSelect: typeof import('./src/components/custom-schema-template/components/SchemaSelect/SchemaSelect.vue')['default']
    SchemaString: typeof import('./src/components/custom-schema-template/components/SchemaString/SchemaString.vue')['default']
    SchemaSwitch: typeof import('./src/components/custom-schema-template/components/SchemaSwitch/SchemaSwitch.vue')['default']
    SchemaUpload: typeof import('./src/components/custom-schema-template/components/SchemaUpload/SchemaUpload.vue')['default']
    WidgetShape: typeof import('./src/components/control/WidgetShape.vue')['default']
  }
}
